routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use App\Http\Controllers\BookController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [BookController::class, 'index']);

Route::group(['middleware' => 'auth', 'prefix' => 'book', 'as' => 'book.'], function() {
    Route::get('create', [BookController::class, 'create'])->name('create');
    Route::post('store', [BookController::class, 'store'])->name('store');
    Route::get('{book:id}/edit', [BookController::class, 'edit'])->name('edit');
    Route::post('{book:id}/update', [BookController::class, 'update'])->name('update');
});

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');

require __DIR__.'/auth.php';

app/Http/Livewire/BookTable.php
<?php

namespace App\Http\Livewire;

use Livewire\Component;
use Livewire\WithPagination;
use App\Livewire\SearchableTable;
use App\Models\Book;
use Illuminate\Support\Facades\Auth;

class BookTable extends Component
{
    use WithPagination, SearchableTable;

    public $title,
           $name,
           $co_authors,
           $publication_date;

    protected $params = [
        ['name' => 'title', 'type' => 'string'],
        ['name' => 'name', 'type' => 'string'],
        ['name' => 'publication_date', 'type' => 'string']
    ];


    public function render()
    {
        $books = new Book::withAuthorName();

        // поиск по соавторам
        if(!empty($this->co_authors)) {
            $books = $books->searchByCoAuthors($this->co_authors);
        }

        // подключаем поиск по столбцам и сортировку
        $books = $this->searchable($books);
        $books = $this->sortable($books, 'title');

        return view('livewire.book-table', ['books' => $books->paginate(10)]);
    }

    public function delete($book_id)
    {
        if(Auth::check()) {
            $book = Book::findOrFail($book_id);
            $book->delete();
        }
        else
            abort(403);
    }
}

app/Livewire/SearchableTable.php
<?php
namespace App\Livewire;

trait SearchableTable
{
    public $order = ['column' => '', 'order' => ''];
    protected $supported_operations = ['!', '<', '>'];

    public function searchable($model)
    {
        foreach($this->params as $param) {
            // значение поля поиска
            $value = $this->{$param['name']};
            // tcли поисковое выражение не передавалось - пропускаем
            if($value == null)
                continue;

            // получаем команду из запроса, если она там есть
            $first_symbol = substr($value, 0, 1);
            $command = false;
            if(in_array($first_symbol, $this->supported_operations))
            {
              $command = ($first_symbol == '!') ? '!=' : $first_symbol;

              // отрезаем команду
              $value = substr($value, 1);
            }

            // условия в зависимости от типа парамтра
            $column = $this->columnToUseInRequest($param['name']);
            $function = 'where';
            $operation = $command ? $command : '=';
            switch($param['type'])
            {
                case 'string':
                    $operation = ($command == '!=') ? 'not like' : 'like';
                    $value = "%{$value}%";
                    break;
                case 'int': break;
                case 'date_day':
                case 'date_month':
                case 'date_year':
                    // явно задаем таблицу, которой принадлежит столбец
                    $column = $model->getQuery()->from . '.created_at';
                    // ...->whereMonth / whereDay / whereYear
                    $function = 'where' . substr($param['type'], strpos($param['type'], '_') + 1);
                    break;
            }

            // если есть объединенный параметр из нескольких таблиц
            if(isset($param['tables'])) {
                foreach($param['tables'] as $key => $table) {
                  $temp_function = ($key === 0) ? $function : "or{$function}";
                  $temp_column = "{$table}.{$column}";

                  $model = $model->$temp_function($temp_column, $operation, $value);
                }
            }
            else
                $model = $model->$function($column, $operation, $value);
        }

        return $model;
    }

    /**
     * Подключает сортировку по столбцам.
     * $model Model
     * string $orderBy столбец начальной сортировки, необязательный параметр
     * string $sort ASC или DESC, по умолчанию DESC
    */
    public function sortable($model, $orderBy = null, $sort = 'DESC')
    {
        if(!empty($this->order['column'])) {
            $model = $model->orderBy($this->order['column'], $this->order['order']);
        }
        if(!is_null($orderBy)) {
            // если задана начальная сортировка
            $model = $model->orderBy($orderBy, $sort);
        }


        return $model;
    }

    /*
     * Меняем сортировку у столбца
    */
    public function changeOrder($column)
    {
        // проставляем сортировку
        $this->order['order'] = ($column !== $this->order['column'] OR $this->order['order'] == 'DESC') ? 'ASC' : 'DESC';
        // и столбец, по которому будем сортировать
        $this->order['column'] = $column;

        $this->render();
    }

    private function columnToUseInRequest($column)
    {
        // если в названии параметра есть __ - меняем его на точку, чтобы получилось таблица.столбец
        $column = str_replace('__', '.', $column);

        return $column;
    }
}

resources/views/livewire/book-table.blade.php
<div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
  <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
    <table class="min-w-full divide-y divide-gray-200">
      <thead class="bg-gray-50">
        <tr>
            @foreach([['title', 'Title', 'sortable'],
                      ['name', 'Authors', 'sortable'],
                      ['co_authors', 'Co-authors'],
                      ['publication_date', 'Publication date', 'sortable']] as $th)
                    <th class="px-6 pt-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider @if(isset($th[2])) sortable cursor-pointer @endif" @if(isset($th[2])) wire:click="changeOrder('{{ $th[0] }}')" @endif>{{ __($th[1]) }}</th>
            @endforeach
            @auth
                <th></th>
                <th></th>
            @endauth
        </tr>
        <tr>
          <th scope="col" class="px-6 pb-2 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
              <input class="shadow appearance-none border rounded w-full py-0 px-0" type="text" wire:model.debounce.500ms="title">
          </th>
          <th scope="col" class="px-6 pb-2 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
              <input class="shadow appearance-none border rounded w-full py-0 px-0" type="text" wire:model.debounce.500ms="name">
          </th>
          <th scope="col" class="px-6 pb-2 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
              <input class="shadow appearance-none border rounded w-full py-0 px-0" type="text" wire:model.debounce.500ms="co_authors">
          </th>
          <th scope="col" class="px-6 pb-2 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
              <input class="shadow appearance-none border rounded w-full py-0 px-0" type="text" wire:model.debounce.500ms="publication_date">
          </th>
          @auth
              <th></th>
              <th></th>
          @endauth
        </tr>
      </thead>
      <tbody class="bg-white divide-y divide-gray-200">
        @foreach($books as $book)
            <tr>
                <td class="px-6 py-4 whitespace-nowrap">
                    <div class="flex items-center">
                        <div class="text-sm font-medium text-gray-900">
                            {{ $book->title }}
                        </div>
                    </div>
                </td>
                <td class="px-6 py-4 whitespace-nowrap">
                    <div class="text-sm text-gray-900">{{ $book->name }}</div>
                </td>
                <td class="px-6 py-4 whitespace-nowrap">
                    @foreach($book->coAuthors as $coAuthor)
                        <div class="text-sm text-gray-900">{{ $coAuthor->name }}</div>
                    @endforeach
                </td>
                <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                    <div class="text-sm text-gray-900" date="{{ $book->publication_date }}">{{ $book->publication_date->toFormattedDateString() }}</div>
                </td>
                @auth
                    <td class="px-3 py-4 whitespace-nowrap text-right text-sm font-medium">
                        <a href="{{ route('book.edit', $book->id) }}" class="text-indigo-600 hover:text-indigo-900 edit-button">Edit</a>
                    </td>
                    <td class="px-3 py-4 pr-5 whitespace-nowrap text-right text-sm font-medium">
                        <a href="#" wire:click="delete({{ $book->id }})" class="text-red-600 hover:text-red-900">Delete</a>
                    </td>
                @endauth
            </tr>
        @endforeach
      </tbody>
    </table>
  </div>
  <div class="pt-5 p-3">{{ $books->links() }}</div>
</div>